@apiURL = http://localhost:4001/api/v1
#####create new user
####
POST {{apiURL}}/auth/register
Content-Type: application/json

{
  "fname": "deepgh",
  "lname": "deepgh",
  "email": "deepgh@gmail.com",
  "phone": "0451812",
  "password": "1234",
  "cpassword": "1234"
}


###

POST {{apiURL}}/auth/login
Content-Type: application/json

{
  "email": "tester@gmail.com", 
  "password": "1234"

}

###
GET {{apiURL}}/user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlZXBnaEBnbWFpbC5jb20iLCJsbmFtZSI6ImRlZXBnaCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc1OTc1MTg0MiwiZXhwIjoxNzYwMzU2NjQyfQ.ygb6RgbI9tBUkm7bHunkLmf6CnkiXeMUqnskQ6lF1bg

{

}

###
 GET {{apiURL}}/category
Content-Type: application/json

{
  
}

#####
POST {{apiURL}}/products
Content-Type: application/json

{
  "name": "Nokia Lumia",
  "description": "Ancient Beast",
  "price": 300,
  "stock": 3,
  "category": "68c8f01555ede480a0121d5e",
  "images": ["https://msblogs.thesourcemediaassets.com/2013/08/5543.Lumia925Blk34Combo3ATT_5F00_LR_5F00_1CC4F241.jpg", "https://cdn.mos.cms.futurecdn.net/irLuBqtehijKJiyd8DWum8.jpg"],
  "speacility": "Doesnt break at all"
}


#####
GET {{apiURL}}/products



#####
#### Update product
PATCH {{apiURL}}/products
Content-Type: application/json

{
  "id": "68cfbe279b2684f7f1118e28", 
  "description": "Phone is now discontinued."
}


#####
#### Delete product
DELETE {{apiURL}}/products
Content-Type: application/json

{
  "id": "68cfbe279b2684f7f1118e28"
}

#####
#### place order
POST {{apiURL}}/order
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlckBnbWFpbC5jb20iLCJmbmFtZSI6IlRlc3QiLCJsbmFtZSI6InRlc3QiLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NjA0MzQwMzgsImV4cCI6MTc2MTAzODgzOH0.W8B8j1UgmYOUYDE6F4NoAycMWSsW-vwxTOvn3t_80-w

{
  "customerId": "68e45e91d2c77b22c1fa493e",
  "items": [
    
    {
      "productId": "68edb97527e2ec70a80c6dde",
      "quantity": 1,
      "price": 1500
    }
  ],
  "total":1500
}


#####
#### get my all orders
GET {{apiURL}}/order?id=68e45e91d2c77b22c1fa493e
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlckBnbWFpbC5jb20iLCJmbmFtZSI6IlRlc3QiLCJsbmFtZSI6InRlc3QiLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NjA1MjIxMzcsImV4cCI6MTc2MTEyNjkzN30.jIVGPJUP7vgVRG0TBB_rMgTc1o-Td2tHg25VKU5zUEg

###### get featured products
GET {{apiURL}}/products/featured-products
Content-Type: application/json


###### get product details of subcategory
GET {{apiURL}}/category/vlogging
Content-Type: application/json
